version: '3.8'

services:
  # 前端应用服务
  flow-rpa-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flow-rpa-platform
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_NAME=龙行RPA平台
      - REACT_APP_VERSION=1.0.0
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - rpa-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 网络配置
networks:
  rpa-network:
    driver: bridge

# 如果需要数据库，取消下面的注释
# volumes:
#   postgres_data:
